### ISSUE TITLE
金额有限制

### ISSUE THREAD

**Issue by uutan** [PingPlusPlus/pingpp-php#16]
在支付时，金额1.00,需要去掉点，写成100. 但总金额却不让大于10000.按这样算，只支持0.1到99.99元之间的支付是正确的。而费上8千的，无法完成支付。

**Comment by takato3000** [comment]
@uutan 个人开发者是有限额的，具体限额可以查阅官网的Dashboard

**Comment by toby1991** [comment]
发起退款，因为退款金额 10000 超过了最大退款限额
test是这样，不知道live是不是这样

**Comment by samurai00** [comment]
@toby1991 测试模式生产模式都没有这种限制。（另外，这上面的话题是个人开发者相关的，这个早就已经不支持了。）
