### ISSUE TITLE
关于对象数据格式化

### ISSUE THREAD

**Issue by henter** [PingPlusPlus/pingpp-php#21]
没找到显式的方法可以调。。
只能尝试以下：

尝试拿到json
```
$json = (string)$charge;
```

但是，尝试拿到array时就醉了。。出来一大坨***
```
$array = (array)$charge;
```

所以要先转json再转array ？ 
```
$array = json_decode((string)$charge, true);
```
= =！！

**Comment by samurai00** [comment]
不知道你要转成 `array` 做什么，如果只是取里面的元素的话，可以直接取的，`$charge['id']` 。

**Comment by henter** [comment]
我想把charge对象保存下来而已 😳

Sent from Outlook




On Mon, Jun 15, 2015 at 4:55 AM -0700, "afon" <notifications@github.com> wrote:












不知道你要转成 array 做什么，如果只是取里面的元素的话，可以直接取的，$charge['id'] 。

**Comment by samurai00** [comment]
保存到数据库吗？保存到数据库的话，你可以选择保存 JSON 格式的。

**Comment by henter** [comment]
好吧 谢啦

Sent from Outlook




On Mon, Jun 15, 2015 at 5:24 AM -0700, "afon" <notifications@github.com> wrote:












保存到数据库吗？保存到数据库的话，你可以选择保存 JSON 格式的。
