### ISSUE TITLE
请问 Server SDK 可以通过接口调用，设置某个订单已付款吗？

### ISSUE THREAD

**Issue by dcb9** [PingPlusPlus/pingpp-php#24]

**Comment by samurai00** [comment]
不可以手动设置为已付款。Live 模式只能通过客户端真是付款。Test 模式只能通过客户端模拟付款。

**Comment by dcb9** [comment]
嗯，由于我在写测试的时候，需要用程序手动把该订单设置为已付款的状态，这个肯定只是运行在测试环境里面的。

看了下客户端代码，使用 `GET` 请求 `https://api.pingxx.com/notify/charges/CHARGE_ID?livemode=false` 貌似可以达到该效果。

**Comment by samurai00** [comment]
@dcb9 是的，这样是可以的。
