### ISSUE TITLE
client的参数怎么传入server?

### ISSUE THREAD

**Issue by wonleing** [PingPlusPlus/pingpp-php#25]
我在调试ping-html5-one中的demo/demo.php,在pingpp_one.init中传入的open_id:'def',
在server端使用的ping-php中的example/pay.php,$input_data['open_id'];并得不到本应该传入的值。前端报invalid_charge:no_charge_id

**Comment by wonleing** [comment]
很奇怪 order_id这个参数就可以传进来，但charge_param和open_id却不行

**Comment by samurai00** [comment]
你把整个 `php://input` 打印出来没有这样的结构吗?
```
{
    "channel":"alipay_wap",
    "amount":10,
    "order_no":"no1234567890",
    "open_id":"",
    "a":1,
    "b":2
}
```
