### ISSUE TITLE
ping-html-one与ping-php的页面必须放在一个server上吗？

### ISSUE THREAD

**Issue by wonleing** [PingPlusPlus/pingpp-php#26]
分别放在两个server上会报json decode error, network error

**Comment by samurai00** [comment]
跨域了，你需要在服务端加跨域头
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS

**Comment by wonleing** [comment]
查到了这样的描述
var invocation = new XMLHttpRequest();
var url = 'http://bar.other/resources/public-data/';
function callOtherDomain() {
  if(invocation) {    
    invocation.open('GET', url, true);
    invocation.onreadystatechange = handler;
    invocation.send(); 
  }
}

请明示如何加到client端？

**Comment by samurai00** [comment]
你在服务端这个接口的 response header 里加这个就好了
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
```
