### ISSUE TITLE
在管理平台申请的退款一直显示“退款中”

### ISSUE THREAD

**Issue by wonleing** [PingPlusPlus/pingpp-php#28]
在管理平台页面上操作的退款实际上退款很快就已经到帐了，但页面一直显示“退款中”，而且平台也没有call退款的webhooks。
这很严重，根本不敢用退款功能，因为不能与自己数据库帐目同步！

**Comment by samurai00** [comment]
什么渠道的？有些渠道是他们的接口提供的数据跟他们自己的后台有延时。
