### ISSUE TITLE
你好，有laravel框架直接可以用的包么？

### ISSUE THREAD

**Issue by OranTing** [PingPlusPlus/pingpp-php#29]
如题，谢谢了。

**Comment by samurai00** [comment]
没有直接可以用的包。你可以尝试手动接一下。

**Comment by samurai00** [comment]
我们的 SDK 支持 composer 的，应该可以直接导入到 Laravel 的。
或者你可以看一下这个视频 https://laravist.com/series/accept-payment-online-with-pingxx

**Comment by lyt8384** [comment]
其实自己写一个也很快的。我就直接封了一个，目前能满足自己的基本需求
