### ISSUE TITLE
【获取签名】webhook获取签名有时无法获取的问题

### ISSUE THREAD

**Issue by rdcxzc** [PingPlusPlus/pingpp-php#33]
在php的demo中获取ping++签名的时候会出现偶发性的无法获取签名到时验签失败
经过多次尝试将以下代码
`$signature = isset($headers['X-Pingplusplus-Signature']) ? $headers['X-Pingplusplus-Signature'] : NULL;`
改为：
`$signature = isset($headers['x-pingplusplus-signature']) ? $headers['x-pingplusplus-signature'] : (isset($headers['X-Pingplusplus-Signature']) ? $headers['X-Pingplusplus-Signature'] : NULL);`

望采纳

**Comment by samurai00** [comment]
这个在服务器为 apache 的时候才会有这种情况。nginx 时，不会。马上会做相应修复。
