### ISSUE TITLE
readme中给出的composer安装方式是错误的

### ISSUE THREAD

**Issue by jhdxr** [PingPlusPlus/pingpp-php#34]
`composer install`代表的是在存在composer.lock时，以其为准安装依赖，否则等同于`composer update` （具体区别可以参考 https://tech.jhdxr.com/archives/introduce-to-composer-install-and-update/ ），因此目前文档中给出的安装方式在项目已经安装过依赖时是无效的（尽管composer会给出警告，但不会安装依赖）。

readme里所提到的对应的正确命令应该是`composer require pingplusplus/pingpp-php:dev-master` 这条命令会自动更新composer.json，安装依赖并更新composer.lock，并且不影响其他依赖。

**Comment by samurai00** [comment]
谢谢提醒
